Add Pager component
the-deep/deep-ui pull request #13
Opened 2021-04-12 09:45 UTC by samshara

fixes https://github.com/the-deep/client/issues/1457

2021-04-12 10:40 UTC, tnagorra commented on src/index.tsx
> +export { default as Pager } from './components/Pager';
Exports should be sorted in alphabetical order

2021-04-12 10:42 UTC, tnagorra commented on src/components/Pager/index.tsx
> +    { label: '100 / page', key: 100 },
I think we should remove these 2 options

2021-04-12 10:44 UTC, tnagorra commented on src/components/Pager/index.tsx
> +import React from 'react';
Please refer to this updated file
https://github.com/toggle-corp/toggle-ui/blob/dfb69ebe734e7a90cbd2424c2abc9c2c85848561/src/components/Pager/index.tsx

2021-04-12 10:47 UTC, tnagorra requested changes
Need to make Pager up-to-date with toggle-ui

2021-04-13 10:21 UTC, tnagorra commented on src/stories/Pager.stories.tsx
> +    const [{ activePage, maxItemsPerPage }, handleArgsChange] = useArgs();
Why read maxItemsPerPage?

2021-04-15 06:08 UTC, tnagorra commented
Needs more work on the styling

2021-04-23 05:03 UTC, frozenhelium approved these changes

2021-04-23 06:05 UTC, tnagorra commented on src/components/Pager/index.tsx
> +                    onClick={() => onActivePageChange(activePage + 1)}
Here, you can use `name={activePage + 1}`

2021-04-23 06:05 UTC, tnagorra commented on src/components/Pager/index.tsx
> +    const minOption = Math.min(0, ...itemsPerPageOptions.map((opt) => opt.key));
maybe we should memoize this

2021-04-23 11:25 UTC, AdityaKhatri approved these changes

2021-04-28 04:19 UTC, merged