Add Checkbox component
the-deep/deep-ui pull request #14
Opened 2021-04-13 08:40 UTC by frozenhelium

- Update spacing related CSS variables
- Add surface colors
- Add more option for spacing and font-size related variables

2021-04-13 10:28 UTC, tnagorra commented on src/components/Checkbox/Checkmark/index.tsx
> +    );
Why use _cs function here?

2021-04-13 10:32 UTC, tnagorra commented on src/components/Checkbox/index.tsx
> +function Checkbox<N extends string>(props: CheckboxProps<N>) {
Maybe we should also extend number here?

2021-04-14 04:00 UTC, tnagorra requested changes
Need to check generic type for Checkbox

2021-04-14 06:43 UTC, frozenhelium commented
@tnagorra Done!!!

2021-04-15 05:37 UTC, tnagorra approved these changes

2021-04-15 05:40 UTC, AdityaKhatri commented on src/index.tsx
> +export { default as Checkbox } from './components/Checkbox';
Plz sort

2021-04-15 05:44 UTC, merged