Add collapsible container
the-deep/deep-ui pull request #15
Opened 2021-04-13 11:07 UTC by frozenhelium

2021-04-13 11:21 UTC, tnagorra requested changes
We should add "collapsed on initial state" prop

2021-04-15 05:54 UTC, tnagorra approved these changes

2021-04-15 06:01 UTC, AdityaKhatri approved these changes

2021-04-15 06:01 UTC, AdityaKhatri approved these changes

2021-04-15 06:02 UTC, merged