Add radio and segment input
the-deep/deep-ui pull request #26
Opened 2021-04-30 11:01 UTC by frozenhelium

2021-05-03 17:16 UTC, AdityaKhatri commented on src/components/RadioInput/index.tsx
> +            value: key === value,
Pass disabled and disable the input

2021-05-04 05:02 UTC, frozenhelium commented on src/components/RadioInput/index.tsx
> +            value: key === value,
Done!

2021-05-04 05:39 UTC, AdityaKhatri commented
Add readonly

2021-05-04 07:30 UTC, frozenhelium commented
@AdityaKhatri done!

2021-05-04 12:59 UTC, AdityaKhatri approved these changes

2021-05-04 16:19 UTC, tnagorra commented on src/components/Button/index.tsx
> +    readOnly?: boolean;
Button should not have a readOnly field.
What does this do?

2021-05-04 16:22 UTC, tnagorra commented on src/stories/RadioInput.stories.tsx
> +};
Please add more stories.

2021-05-04 16:22 UTC, tnagorra commented on src/stories/SegmentInput.stories.tsx
> +    },
Please add more stories

2021-05-05 05:06 UTC, subinasr approved these changes

2021-05-05 11:46 UTC, tnagorra requested changes

2021-05-05 11:46 UTC, tnagorra commented on src/stories/RadioInput.stories.tsx
> +};
Please also add stories to show error and hint

2021-05-05 11:46 UTC, tnagorra commented on src/stories/SegmentInput.stories.tsx
> +};
Please also add stories to show error and hint

2021-05-05 11:53 UTC, tnagorra approved these changes

2021-05-05 11:55 UTC, merged