Add DateRangeOutput component
the-deep/deep-ui pull request #34
Opened 2021-05-14 08:25 UTC by frozenhelium

2021-05-14 12:03 UTC, AdityaKhatri commented on src/components/DateRangeOutput/index.tsx
> +    endDate: DateOutputProps['value'];
@frozenhelium we need to handle cases where there are no startDate or no EndDate or both are absent.

2021-05-14 12:04 UTC, AdityaKhatri commented on src/components/DateRangeOutput/index.tsx
> +            <div className={styles.separator}>-</div>
Hide separator based on availability of start or end date

2021-05-14 12:04 UTC, AdityaKhatri requested changes
Fix change requests

2021-05-21 07:10 UTC, samshara approved these changes

2021-05-25 08:34 UTC, subinasr approved these changes

2021-05-26 04:08 UTC, tnagorra approved these changes

2021-05-27 14:32 UTC, merged