Feature/calendar
the-deep/deep-ui pull request #68
Opened 2021-07-07 09:49 UTC by frozenhelium

### This PR ensures that there are
- [x] No unnecessary console logs
- [x] No unwanted comments
- [x] No typos
- [x] `yarn typecheck` shows no issue
- [x] `yarn lint` shows no issue

### This PR adds one or more new components / utils

- [x] Add the newly created component and its props to exports
- [x] Write story for newly created component(s)
- [x] No empty files

### This PR fixes or updates existing components / utils

- [x] Update / add story to reflect the changes
- [x] Doesn't introduce breaking changes

### Beta release vXX.XX.XX-beta.YY
- [ ] Add a commit for beta release

2021-07-08 03:56 UTC, samshara approved these changes

2021-07-08 04:05 UTC, AdityaKhatri commented
To be fixed:
* Month cannot be selected
* Predefined date ranges should have different colors on hover
* Bottom align year and month selection in popup
* Selected date is not shown in date select
* Date input should go to selected month if value is already there

2021-07-08 04:05 UTC, AdityaKhatri requested changes
Fix few items

2021-07-08 05:02 UTC, frozenhelium commented
@AdityaKhatri done!

2021-07-08 09:30 UTC, tnagorra commented on src/components/Calendar/CalendarDate/index.tsx
> +    date: number;
Shouldn't this be day?
```suggestion
    day: number;
```

2021-07-08 09:35 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +    return new Date(year, month + 1, 0).getDate();
Let's add a comment why we did this.

2021-07-08 09:41 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +function getDates(year: number, month: number) {
Let's return a list of object:
```
// Example
{ day: number, month: 'prev' | 'current' | 'next' }[]
```

2021-07-08 09:42 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +    dateRenderer?: (p: P) => React.ReactElement;
```suggestion
    dateRenderer?: (prop: P) => React.ReactElement;
```

2021-07-08 09:57 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +];
Let's also add value property that computes the required value

2021-07-08 09:59 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +                return undefined;
Do we need to return undefined?

2021-07-08 11:43 UTC, subinasr approved these changes

2021-07-09 03:23 UTC, frozenhelium commented on src/components/Calendar/CalendarDate/index.tsx
> +    date: number;
day represents day of week in js

2021-07-09 04:08 UTC, frozenhelium commented on src/components/DateRangeInput/index.tsx
> +                return undefined;
Apparently

2021-07-09 04:19 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +                return undefined;
oh no!

2021-07-09 06:24 UTC, tnagorra requested changes

2021-07-09 06:24 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +    // Setting date to 0 will switch the date to last day of previous month
We should have an alternative name to differentiate between "गते" and "मिति"

2021-07-09 06:24 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +    const today = new Date();
We should move today at the start 
and use it's value on current as fallback. Just for sematics.

2021-07-09 06:24 UTC, tnagorra commented on src/components/Calendar/index.tsx
> +                            <div className={styles.dayContainer}>
We need a key here!

2021-07-09 06:24 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +        endDate: !tempStartDate ? value?.endDate : undefined,
Let's add a comment here!

2021-07-09 06:24 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +    const handleCalendarDateClick: CalendarProps<never>['onDateClick'] = React.useCallback(
This function is complicated. It does a lot of things.
Let's try to break this down.

2021-07-09 06:24 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +            }
Maybe this return is not placed correctly.

2021-07-09 09:29 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +            });
I still don't like calling sideEffects inside setState. I don't  know if it's the correct thing to do.

2021-07-09 09:29 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +            });
@AdityaKhatri any thoughts?

2021-07-09 09:40 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +            });
Maybe try using useReducer and move the side-effects there? Idk if we should call sideEffects there as well

2021-07-09 09:41 UTC, tnagorra commented on src/components/DateRangeInput/index.tsx
> +            });
Looks like reducer function should also be pure

2021-07-09 13:22 UTC, tnagorra approved these changes

2021-07-11 13:01 UTC, AdityaKhatri approved these changes

2021-07-11 13:01 UTC, merged