Feature/tabs
the-deep/deep-ui pull request #7
Opened 2021-03-29 04:46 UTC by AdityaKhatri

2021-03-29 05:07 UTC, tnagorra commented on src/index.tsx
>  import './styles.css';
The sorting should place imports from same file together

2021-03-29 05:11 UTC, tnagorra commented on src/stories/Tabs.stories.tsx
> +const Template: Story<TabsProps<string> & { disableTabTwo: boolean }> = () => {
We need to add stories for each individual component

2021-03-29 10:54 UTC, subinasr approved these changes

2021-04-09 05:07 UTC, tnagorra requested changes
Please use new RawButton

2021-04-09 05:51 UTC, tnagorra approved these changes

2021-04-09 06:14 UTC, merged