Remove label typing pollution from RawInput in FileInput
the-deep/deep-ui pull request #74
Opened 2021-07-14 11:24 UTC by samshara

### This PR ensures that there are
- [x] No unnecessary console logs
- [x] No unwanted comments
- [x] No typos
- [x] `yarn typecheck` shows no issue
- [x] `yarn lint` shows no issue

### This PR adds one or more new components / utils

- [x] Add the newly created component and its props to exports
- [x] Write story for newly created component(s)
- [x] No empty files

### This PR fixes or updates existing components / utils

- [x] Update / add story to reflect the changes
- [x] Doesn't introduce breaking changes

### Beta release vXX.XX.XX-beta.YY
- [x] Add a commit for beta release

2021-07-19 09:30 UTC, frozenhelium approved these changes

2021-07-21 09:29 UTC, tnagorra requested changes
There's conflict in package.json

2021-07-23 05:33 UTC, tnagorra approved these changes

2021-07-23 06:09 UTC, tnagorra commented on src/components/FileInput/index.tsx
> +type InheritedProps<T> = (Omit<InputContainerProps, 'input'> & Omit<RawInputProps<T>, 'onChange' | 'value' | 'label'>);
Why not do this change for other inputs as well?

2021-07-23 06:09 UTC, tnagorra requested changes
Let's do this change for all of the inputs or find a way so that this kind of problem doesn't occur next time in the future.

2021-08-20 10:58 UTC, tnagorra commented
The issue this PR addresses has been fixed in another PR

2021-08-20 10:58 UTC, closed without merging